spring:
  application:
    name: rabbit-demo

  security:
    oauth2:
      client:
        registration:
          rabbitmq-client:
            client-id: myapp
            client-secret: mysecret
            authorization-grant-type: client_credentials
            provider: my-oauth-provider

        provider:
          my-oauth-provider:
            token-uri: https://myprovider/token

rabbitmq:
    host: localhost
    port: 5672
    vhost: dev-domain1